name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
    steps:
        - uses: actions/checkout@v2
        - name: Install Vercel CLI
          run: pnpm install --global vercel
        - name: Install Dependencies
          run: pnpm install
        - name: Build Project
          run: pnpm run build
        # - name: Deploy to Vercel
        #   run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}